# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import textrepo_client
from textrepo_client.api.task_api import TaskApi  # noqa: E501
from textrepo_client.rest import ApiException


class TestTaskApi(unittest.TestCase):
    """TaskApi unit test stubs"""

    def setUp(self):
        self.api = TaskApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_document_recursively(self):
        """Test case for delete_document_recursively

        Delete a document including its metadata, files, versions and contents. Contents are only only deleted when not referenced by any other versions.  # noqa: E501
        """
        pass

    def test_get_document_metadata(self):
        """Test case for get_document_metadata

        Find metadata of document by external ID, with header links to original and parent resource  # noqa: E501
        """
        pass

    def test_get_file_metadata(self):
        """Test case for get_file_metadata

        Find metadata of file by external ID and file type, with header links to original, parent and type resource  # noqa: E501
        """
        pass

    def test_get_latest_file_version_content(self):
        """Test case for get_latest_file_version_content

        Find contents of latest file version by external ID and file type, with header links to version history, parent and type resource  # noqa: E501
        """
        pass

    def test_import_document_contents_for_file_with_type(self):
        """Test case for import_document_contents_for_file_with_type

        Import file as the current version for {typeName} of document referenced by {externalId} without indexing  # noqa: E501
        """
        pass

    def test_index_all(self):
        """Test case for index_all

        Index all files by type  # noqa: E501
        """
        pass

    def test_index_document(self):
        """Test case for index_document

        Index file of document by externalId and file type  # noqa: E501
        """
        pass

    def test_index_single_index(self):
        """Test case for index_single_index

        Index all files of a single index  # noqa: E501
        """
        pass

    def test_post_identifiers(self):
        """Test case for post_identifiers

        """
        pass

    def test_put_identifiers(self):
        """Test case for put_identifiers

        """
        pass


if __name__ == '__main__':
    unittest.main()
