"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import textrepo_client
from textrepo_client.api.register_api import RegisterApi  # noqa: E501


class TestRegisterApi(unittest.TestCase):
    """RegisterApi unit test stubs"""

    def setUp(self):
        self.api = RegisterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_identifiers(self):
        """Test case for post_identifiers

        """
        pass

    def test_put_identifiers(self):
        """Test case for put_identifiers

        """
        pass


if __name__ == '__main__':
    unittest.main()
