"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import textrepo_client
from textrepo_client.api.index_api import IndexApi  # noqa: E501


class TestIndexApi(unittest.TestCase):
    """IndexApi unit test stubs"""

    def setUp(self):
        self.api = IndexApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_index_all(self):
        """Test case for index_all

        Index all files by type  # noqa: E501
        """
        pass

    def test_index_document(self):
        """Test case for index_document

        Index file of document by externalId and file type  # noqa: E501
        """
        pass

    def test_index_single_index(self):
        """Test case for index_single_index

        Index all files of a single index  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
