# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import textrepo_client
from textrepo_client.api.files_api import FilesApi  # noqa: E501
from textrepo_client.rest import ApiException


class TestFilesApi(unittest.TestCase):
    """FilesApi unit test stubs"""

    def setUp(self):
        self.api = FilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete2(self):
        """Test case for delete2

        Delete document metadata entry  # noqa: E501
        """
        pass

    def test_delete3(self):
        """Test case for delete3

        Delete file  # noqa: E501
        """
        pass

    def test_get5(self):
        """Test case for get5

        Retrieve file metadata  # noqa: E501
        """
        pass

    def test_get6(self):
        """Test case for get6

        Retrieve file  # noqa: E501
        """
        pass

    def test_get_versions(self):
        """Test case for get_versions

        Retrieve file versions, newest first  # noqa: E501
        """
        pass

    def test_post2(self):
        """Test case for post2

        Not allowed to post metadata: use put instead  # noqa: E501
        """
        pass

    def test_post3(self):
        """Test case for post3

        Create file  # noqa: E501
        """
        pass

    def test_put1(self):
        """Test case for put1

        Create or update file metadata entry  # noqa: E501
        """
        pass

    def test_put2(self):
        """Test case for put2

        Create or update file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
