# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import textrepo_client
from textrepo_client.api.import_api import ImportApi  # noqa: E501
from textrepo_client.rest import ApiException


class TestImportApi(unittest.TestCase):
    """ImportApi unit test stubs"""

    def setUp(self):
        self.api = ImportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_import_document_contents_for_file_with_type(self):
        """Test case for import_document_contents_for_file_with_type

        Import file as the current version for {typeName} of document referenced by {externalId} without indexing  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
