"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import textrepo_client
from textrepo_client.api.contents_api import ContentsApi  # noqa: E501


class TestContentsApi(unittest.TestCase):
    """ContentsApi unit test stubs"""

    def setUp(self):
        self.api = ContentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_version_contents_is_not_allowed(self):
        """Test case for delete_version_contents_is_not_allowed

        Not allowed to delete contents of version: delete version instead  # noqa: E501
        """
        pass

    def test_get_contents(self):
        """Test case for get_contents

        Retrieve contents  # noqa: E501
        """
        pass

    def test_get_version_contents(self):
        """Test case for get_version_contents

        Retrieve version contents  # noqa: E501
        """
        pass

    def test_post_version_contents_is_not_allowed(self):
        """Test case for post_version_contents_is_not_allowed

        Not allowed to post contents: post new version instead  # noqa: E501
        """
        pass

    def test_put_version_contents_is_not_allowed(self):
        """Test case for put_version_contents_is_not_allowed

        Not allowed to put contents of version: post new version instead  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
