"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import textrepo_client
from textrepo_client.api.types_api import TypesApi  # noqa: E501


class TestTypesApi(unittest.TestCase):
    """TypesApi unit test stubs"""

    def setUp(self):
        self.api = TypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_type(self):
        """Test case for create_type

        Create type  # noqa: E501
        """
        pass

    def test_delete_type(self):
        """Test case for delete_type

        Delete type  # noqa: E501
        """
        pass

    def test_get_type(self):
        """Test case for get_type

        Retrieve types  # noqa: E501
        """
        pass

    def test_get_types(self):
        """Test case for get_types

        Retrieve types  # noqa: E501
        """
        pass

    def test_put_type(self):
        """Test case for put_type

        Create or update type  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
