"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import textrepo_client
from textrepo_client.model.form_type import FormType


class TestFormType(unittest.TestCase):
    """FormType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFormType(self):
        """Test FormType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FormType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
