# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import textrepo_client
from textrepo_client.api.types_api import TypesApi  # noqa: E501
from textrepo_client.rest import ApiException


class TestTypesApi(unittest.TestCase):
    """TypesApi unit test stubs"""

    def setUp(self):
        self.api = TypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete4(self):
        """Test case for delete4

        Delete type  # noqa: E501
        """
        pass

    def test_get7(self):
        """Test case for get7

        Retrieve types  # noqa: E501
        """
        pass

    def test_get_all(self):
        """Test case for get_all

        Retrieve types  # noqa: E501
        """
        pass

    def test_post4(self):
        """Test case for post4

        Create type  # noqa: E501
        """
        pass

    def test_put3(self):
        """Test case for put3

        Create or update type  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
