# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import textrepo_client
from textrepo_client.api.dashboard_api import DashboardApi  # noqa: E501
from textrepo_client.rest import ApiException


class TestDashboardApi(unittest.TestCase):
    """DashboardApi unit test stubs"""

    def setUp(self):
        self.api = DashboardApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_count_documents_by_metadata_key(self):
        """Test case for count_documents_by_metadata_key

        Get document count breakdown by metadata key (yields Map: key -> count)  # noqa: E501
        """
        pass

    def test_count_documents_by_metadata_value(self):
        """Test case for count_documents_by_metadata_value

        Get document count breakdown by metadata value for given metadata key  # noqa: E501
        """
        pass

    def test_find_orphans(self):
        """Test case for find_orphans

        Find orphans: documents with neither metadata nor any associated files  # noqa: E501
        """
        pass

    def test_get_stats(self):
        """Test case for get_stats

        Get document count overview  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
