# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import textrepo_client
from textrepo_client.api.versions_api import VersionsApi  # noqa: E501
from textrepo_client.rest import ApiException


class TestVersionsApi(unittest.TestCase):
    """VersionsApi unit test stubs"""

    def setUp(self):
        self.api = VersionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_version(self):
        """Test case for create_version

        Create version  # noqa: E501
        """
        pass

    def test_delete_version(self):
        """Test case for delete_version

        Delete version  # noqa: E501
        """
        pass

    def test_delete_version_contents_is_not_allowed(self):
        """Test case for delete_version_contents_is_not_allowed

        Not allowed to delete contents of version: delete version instead  # noqa: E501
        """
        pass

    def test_get_version(self):
        """Test case for get_version

        Retrieve version  # noqa: E501
        """
        pass

    def test_get_version_contents(self):
        """Test case for get_version_contents

        Retrieve version contents  # noqa: E501
        """
        pass

    def test_get_versions(self):
        """Test case for get_versions

        Retrieve file versions, newest first  # noqa: E501
        """
        pass

    def test_post_version_contents_is_not_allowed(self):
        """Test case for post_version_contents_is_not_allowed

        Not allowed to post contents: post new version instead  # noqa: E501
        """
        pass

    def test_put_version_contents_is_not_allowed(self):
        """Test case for put_version_contents_is_not_allowed

        Not allowed to put contents of version: post new version instead  # noqa: E501
        """
        pass

    def test_put_version_is_not_allowed(self):
        """Test case for put_version_is_not_allowed

        Not allowed to update a version: create a new version using POST  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
