# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FormTextRepoFile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'doc_id': 'str',
        'type_id': 'int'
    }

    attribute_map = {
        'doc_id': 'docId',
        'type_id': 'typeId'
    }

    def __init__(self, doc_id=None, type_id=None):  # noqa: E501
        """FormTextRepoFile - a model defined in Swagger"""  # noqa: E501
        self._doc_id = None
        self._type_id = None
        self.discriminator = None
        self.doc_id = doc_id
        self.type_id = type_id

    @property
    def doc_id(self):
        """Gets the doc_id of this FormTextRepoFile.  # noqa: E501


        :return: The doc_id of this FormTextRepoFile.  # noqa: E501
        :rtype: str
        """
        return self._doc_id

    @doc_id.setter
    def doc_id(self, doc_id):
        """Sets the doc_id of this FormTextRepoFile.


        :param doc_id: The doc_id of this FormTextRepoFile.  # noqa: E501
        :type: str
        """
        if doc_id is None:
            raise ValueError("Invalid value for `doc_id`, must not be `None`")  # noqa: E501

        self._doc_id = doc_id

    @property
    def type_id(self):
        """Gets the type_id of this FormTextRepoFile.  # noqa: E501


        :return: The type_id of this FormTextRepoFile.  # noqa: E501
        :rtype: int
        """
        return self._type_id

    @type_id.setter
    def type_id(self, type_id):
        """Sets the type_id of this FormTextRepoFile.


        :param type_id: The type_id of this FormTextRepoFile.  # noqa: E501
        :type: int
        """
        if type_id is None:
            raise ValueError("Invalid value for `type_id`, must not be `None`")  # noqa: E501

        self._type_id = type_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FormTextRepoFile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FormTextRepoFile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
